<!--
 *  Copyright (c) 2021 GraphQL Contributors
 *  All rights reserved.
 *
 *  This source code is licensed under the license found in the
 *  LICENSE file in the root directory of this source tree.
-->
<!DOCTYPE html>
<html lang="en">
<head>
    <title>GraphQL Explorer</title>

    <style>

        html {
            height: 100%;
            margin: 0;
            width: 100%;
            overflow: hidden;
        }
        body {
            height: 100%;
            margin: 0;
            width: 100%;
            overflow: hidden;
        }

        #embedded-sandbox {
            height: 100vh;
        }
    </style>
</head>

<body>
<div style="width: 100%; height: 100%;" id='embedded-sandbox'></div>
<script src="https://embeddable-sandbox.cdn.apollographql.com/_latest/embeddable-sandbox.umd.production.min.js"></script>
<script>
    new window.EmbeddedSandbox({
        target: '#embedded-sandbox',
        initialEndpoint: '<?php echo $uri; ?>',
		initialState: {
			pollForSchemaUpdates: false
		},
        handleRequest: (endpointUrl, options) => {
            options.credentials = 'include';
            return fetch(endpointUrl, options).then(function (response) {
                return response;
            }).then(function (responseBody) {
                try {
                    return JSON.parse(responseBody);
                } catch (error) {
                    return responseBody;
                }
            });
        },


    });
</script>
</body>
</html>
