<!--
 *  Copyright (c) 2021 GraphQL Contributors
 *  All rights reserved.
 *
 *  This source code is licensed under the license found in the
 *  LICENSE file in the root directory of this source tree.
-->
<!DOCTYPE html>
<html lang="en">
<head>
    <title>GraphiQL</title>
    <style>
        body {
            height: 100%;
            margin: 0;
            width: 100%;
            overflow: hidden;
        }

        #graphiql {
            height: 100vh;
        }
    </style>

    <!--
      This GraphiQL example depends on Promise and fetch, which are available in
      modern browsers, but can be "polyfilled" for older browsers.
      GraphiQL itself depends on React DOM.
      If you do not want to rely on a CDN, you can host these files locally or
      include them directly in your favored resource bundler.
    -->
    <script
            crossorigin
            src="https://unpkg.com/react@18/umd/react.production.min.js"
    ></script>
    <script
            crossorigin
            src="https://unpkg.com/react-dom@18/umd/react-dom.production.min.js"
    ></script>

    <!--
      These two files can be found in the npm module, however you may wish to
      copy them directly into your environment, or perhaps include them in your
      favored resource bundler.
     -->
    <link rel="stylesheet" href="https://unpkg.com/graphiql/graphiql.min.css" />
</head>

<body>
<div id="graphiql">Loading...</div>
<script
        src="https://unpkg.com/graphiql/graphiql.min.js"
        type="application/javascript"
></script>
<script>
    const root = ReactDOM.createRoot(document.getElementById('graphiql'));
	// Adjusted headers retrieval as per https://github.com/graphql/graphiql/discussions/3029#discussioncomment-5027611

    // Defines a GraphQL fetcher using the fetch API. You're not required to
    // use fetch, and could instead implement graphQLFetcher however you like,
    // as long as it returns a Promise or Observable.
    function graphQLFetcher(graphQLParams, {headers}) {
        // This example expects a GraphQL server at the path /graphql.
        // Change this to point wherever you host your GraphQL server.
        // return fetch('http://graphql-demo.local/', {
        return fetch('<?php echo $uri; ?>', {
            method: 'post',
            headers: {
                'Accept': 'application/json',
				'Content-Type': 'application/json',
				...headers
            },
            body: JSON.stringify(graphQLParams),
            credentials: 'include',
        }).then(function (response) {
            return response.text();
        }).then(function (responseBody) {
            try {
                return JSON.parse(responseBody);
            } catch (error) {
                return responseBody;
            }
        });
    }

    root.render(
        React.createElement(GraphiQL, {
            fetcher: graphQLFetcher,
            // fetcher: GraphiQL.createFetcher({
            //     url: 'http://graphql-demo.local/',
            // }),
            defaultEditorToolsVisibility: true,
        }),
    );
</script>
</body>
</html>
