<?php

namespace Graphette\Graphette\TypeRegistry\Definition;

use Nette\PhpGenerator\Literal;
use Nette\Utils\Strings;

class AutogeneratedFieldDefinition extends FieldDefinition {

    private ClassTypeDefinition $typeDefinition;

    public function __construct(ClassTypeDefinition $typeDefinition) {
        $this->typeDefinition = $typeDefinition;
    }

    public function getName(): string {
        return Strings::firstLower($this->typeDefinition->getName());
    }

    public function extractFieldDefinition(): array {
        return [
            'type' => new Literal('$this->NonNull($this->get(\'' . $this->typeDefinition->getName() . '\'))')
        ];
    }

}
