<?php

namespace Graphette\Graphette\TypeRegistry\Definition;

use GraphQL\Type\Definition\ObjectType;
use Nette\PhpGenerator\Dumper;
use Nette\PhpGenerator\Literal;
use Nette\Utils\Strings;

class AutogeneratedTypeDefinition extends TypeDefinition {

    /** @var array<ClassTypeDefinition> */
    private array $childTypeDefinitions;

    /** @var array<FieldDefinition> */
    private array $fieldDefinitions;

    private Dumper $dumper;

    /**
     * @param string $name
     * @param array<ClassTypeDefinition> $childTypeDefinitions
     */
    public function __construct(
        string $name,
        array $childTypeDefinitions
    ) {
        parent::__construct($name);

        $this->dumper = new Dumper();
        $this->childTypeDefinitions = $childTypeDefinitions;
    }

    /**
     * @return array<FieldDefinition>
     */
    public function getFieldDefinitions(): array {
        return $this->fieldDefinitions ??= $this->processChildTypeDefinitions();
    }

    /**
     * @return array<FieldDefinition>
     */
    private function processChildTypeDefinitions(): array {
        $fieldDefinitions = [];

        foreach ($this->childTypeDefinitions as $childType) {
            $fieldDefinitions[] = new AutogeneratedFieldDefinition($childType);
        }

        return $fieldDefinitions;
    }

    public function printTypeFactoryMethodBody(): string {
        $definition = [
            'name' => $this->getName(),
            'description' => null,
        ];

        $fieldDefinitions = $this->getFieldDefinitions();

        foreach ($fieldDefinitions as $fieldDefinition) {
            $definition['fields'][$fieldDefinition->getName()] = $fieldDefinition->extractFieldDefinition();
        }


        return 'return new ' . ObjectType::class . '(' . $this->dumper->dump($definition) . ');';

    }

}
